// Generated by gencpp from file challenge1/Completed.msg
// DO NOT EDIT!


#ifndef CHALLENGE1_MESSAGE_COMPLETED_H
#define CHALLENGE1_MESSAGE_COMPLETED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace challenge1
{
template <class ContainerAllocator>
struct Completed_
{
  typedef Completed_<ContainerAllocator> Type;

  Completed_()
    : completed(0.0)  {
    }
  Completed_(const ContainerAllocator& _alloc)
    : completed(0.0)  {
  (void)_alloc;
    }



   typedef float _completed_type;
  _completed_type completed;





  typedef boost::shared_ptr< ::challenge1::Completed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::challenge1::Completed_<ContainerAllocator> const> ConstPtr;

}; // struct Completed_

typedef ::challenge1::Completed_<std::allocator<void> > Completed;

typedef boost::shared_ptr< ::challenge1::Completed > CompletedPtr;
typedef boost::shared_ptr< ::challenge1::Completed const> CompletedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::challenge1::Completed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::challenge1::Completed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::challenge1::Completed_<ContainerAllocator1> & lhs, const ::challenge1::Completed_<ContainerAllocator2> & rhs)
{
  return lhs.completed == rhs.completed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::challenge1::Completed_<ContainerAllocator1> & lhs, const ::challenge1::Completed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace challenge1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::challenge1::Completed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::challenge1::Completed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::challenge1::Completed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::challenge1::Completed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::challenge1::Completed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::challenge1::Completed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::challenge1::Completed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d06af43347051c04c834a8d2318f53e3";
  }

  static const char* value(const ::challenge1::Completed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd06af43347051c04ULL;
  static const uint64_t static_value2 = 0xc834a8d2318f53e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::challenge1::Completed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "challenge1/Completed";
  }

  static const char* value(const ::challenge1::Completed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::challenge1::Completed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 completed\n"
;
  }

  static const char* value(const ::challenge1::Completed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::challenge1::Completed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.completed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Completed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::challenge1::Completed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::challenge1::Completed_<ContainerAllocator>& v)
  {
    s << indent << "completed: ";
    Printer<float>::stream(s, indent + "  ", v.completed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHALLENGE1_MESSAGE_COMPLETED_H
